(() => {
  const REPO_ISSUE_URL = 'https://github.com/alexiusandromedavsgalaxia-lgtm/peaOS.Officialy-certificates/issues/new';
  const STORAGE_KEY = 'peacloud-state-v3';
  const OWNER = 'alexiusandromedavsgalaxia-lgtm';

  function loadState() {
    try {
      const raw = localStorage.getItem(STORAGE_KEY);
      return raw ? JSON.parse(raw) : { user: null, certificates: [], wdp: null };
    } catch {
      return { user: null, certificates: [], wdp: null };
    }
  }

  function saveState(state) {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(state));
  }

  function hex(bytes) {
    return Array.from(bytes, value => value.toString(16).padStart(2, '0')).join('');
  }

  function randomHex(length) {
    const bytes = new Uint8Array(length);
    crypto.getRandomValues(bytes);
    return hex(bytes);
  }

  async function sha512(text) {
    const digest = await crypto.subtle.digest('SHA-512', new TextEncoder().encode(text));
    return hex(new Uint8Array(digest));
  }

  function plusDays(date, days) {
    return new Date(date.getTime() + days * 86400000).toISOString();
  }

  function createCertificateRecord(name) {
    const issued = new Date();
    return {
      id: randomHex(16),
      type: 'SigningCertificate',
      status: 'active',
      serial: randomHex(8),
      issuer_key_id: 'peaOS-r35-issuer-v1',
      issued_at: issued.toISOString(),
      expires_at: plusDays(issued, 90),
      name,
      authentication: 'R35-SHA512'
    };
  }

  async function publishFromForm(event) {
    event.preventDefault();
    event.stopImmediatePropagation();

    const form = event.target;
    const name = form.querySelector('[name="name"]')?.value.trim() || '';
    const error = form.querySelector('#certFormError');
    if (!name) {
      if (error) error.textContent = 'Escribe un nombre.';
      return;
    }

    const record = createCertificateRecord(name);
    const canonical = JSON.stringify({
      id: record.id,
      type: record.type,
      status: record.status,
      serial: record.serial,
      issuer_key_id: record.issuer_key_id,
      issued_at: record.issued_at,
      expires_at: record.expires_at,
      authentication: record.authentication
    });
    record.sha512 = await sha512(canonical);
    record.publication = 'pending';

    const state = loadState();
    state.certificates = Array.isArray(state.certificates) ? state.certificates : [];
    state.certificates.unshift(record);
    saveState(state);

    const payload = JSON.stringify({
      id: record.id,
      type: record.type,
      status: record.status,
      serial: record.serial,
      issuer_key_id: record.issuer_key_id,
      issued_at: record.issued_at,
      expires_at: record.expires_at,
      sha512: record.sha512
    }, null, 2);

    const body = [
      '## peaOS certificate publication request',
      '',
      'This request was generated by peaCloud Certificates.',
      '',
      'Only the authorized repository owner may publish records to the official registry.',
      '',
      'CERTIFICATE_JSON_BEGIN',
      payload,
      'CERTIFICATE_JSON_END',
      '',
      `Generated for: ${name}`
    ].join('\n');

    const url = `${REPO_ISSUE_URL}?title=${encodeURIComponent(`[peaOS Certificate] ${record.id}`)}&body=${encodeURIComponent(body)}`;
    window.location.href = url;
  }

  function decoratePage() {
    const section = document.querySelector('#certificates');
    if (!section) return;
    section.querySelectorAll('.local-badge').forEach(badge => {
      badge.textContent = 'Publication pending';
    });
    section.querySelectorAll('.section-head .muted').forEach(node => {
      if (node.textContent.includes('borradores')) node.textContent = 'published certificates + publication requests.';
    });
    section.querySelectorAll('.stat span').forEach(node => {
      if (node.textContent.trim() === 'borradores') node.textContent = 'pending publication';
    });
  }

  document.addEventListener('submit', event => {
    if (event.target?.id === 'certForm') publishFromForm(event);
  }, true);

  new MutationObserver(decoratePage).observe(document.body, { childList: true, subtree: true });
  decoratePage();

  // Keep the constant explicit so the generated publication flow never points at another repository.
  void OWNER;
})();
